application/controllers/AwardsController.php
<?php
use application\extensions\Translit\Translit;
/**
 * Created by PhpStorm.
 * User: burre
 * Date: 06.04.15
 * Time: 14:45
 */

class AwardsController extends Controller {
    public $layout = 'awards';

    public function init()
    {
        Yii::app()->request->enableCsrfValidation = false;

        return parent::init();
    }

    /**
     * Это нужно для того, чтобы AssetManager переписывал копии скриптов.
     * @param CAction $action
     * @return bool
     */
    protected function beforeAction($action){
        if($_SERVER['REQUEST_METHOD'] == 'OPTIONS'){
            return;
        }
        if(defined('YII_DEBUG') && YII_DEBUG){
            Yii::app()->assetManager->forceCopy = true;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex() {

        $criteria = new CDbCriteria();
        $criteria->condition = 't.ticket_id IS NOT NULL';
        if(Yii::app()->user->isGuest){
            $criteria->addCondition('t.approved = 1');
        }
        $criteria->order = "id ASC";


        $dataProvider=new CActiveDataProvider('Game', array(
            'criteria'=>$criteria,
            'pagination'=>false,
        ));

        $this->render('index', array('dataProvider'=>$dataProvider));
    }

    public function actionGameview($id) {
        $game = Game::model()->findByPk($id);
        if($game){
            $settings = Settings::model()->findByPk(19);
            $pitch_match_url = ($settings)? $settings->value : '';

            $partner = Partner::model()->find('email=:email', array(':email'=>$game->email));
            $this->render('game', array('game'=>$game, 'partner'=>$partner, 'pitch_match_url'=>$pitch_match_url));
        }
    }

    public function actionGetConfParam() {
        echo Yii::app()->conf;
    }

    public function actionRegister() {
        $this->render('register');
    }

    public function actionFile() {
        if($_FILES && file_exists($_FILES['file']['tmp_name']) && $_POST['ticket']){
            $ticket = Ticket::model()->find('code=:code', array(':code'=>$_POST['ticket']));
            if($ticket){
                if($_FILES['file']['type'] != 'image/jpg' && $_FILES['file']['type'] != 'image/jpeg' && $_FILES['file']['type'] != 'image/png'){
                    http_response_code(400);
                    echo json_encode(array('error'=>'Wrong image format, please add JPG or PNG.'));
                    return;
                }

                /**
                 * checking 100x100 icon
                 */
//                if(isset($_POST['type']) && $_POST['type'] == 'icon'){
//                    $fileinfo = getimagesize($_FILES['file']['tmp_name']);
//                    if($fileinfo[0] != $fileinfo[1] || $fileinfo[0] != 100){
//                        echo json_encode($fileinfo);
//                        return;
//                    }
//                }

                if(!is_dir(Yii::app()->params['htdocsPath'].'/files/'.Yii::app()->conf)){
                    mkdir(Yii::app()->params['htdocsPath'].'/files/'.Yii::app()->conf);
                    mkdir(Yii::app()->params['htdocsPath'].'/files/'.Yii::app()->conf.'/temp');
                    mkdir(Yii::app()->params['htdocsPath'].'/files/'.Yii::app()->conf.'/ticket');
                }

                $path = Yii::app()->params['htdocsPath'].'/files/'.Yii::app()->conf.'/temp/'.$ticket->id;
                if(!is_dir($path)){
                    mkdir($path);
                }

                $fname = Translit::transliterate($_FILES['file']['name']);
                $fpath =  $path.'/'.$fname;
                if(move_uploaded_file($_FILES['file']['tmp_name'], $fpath)){
                    $result = array(
                        "ticket" => $_POST['ticket'],
                        "name" => $fname,
                        "path" => $fpath,
                        "created" => date('Y-m-d h:i:s', time())
                    );
                    echo json_encode($result);
                }else{
                    http_response_code(400);
                    echo json_encode(array('error'=>'Error. Unable to save file.'));
                }
            }else{
                http_response_code(400);
                echo json_encode(array('error'=>'Error. Ticket was not found.'));
            }
        }else{
            http_response_code(400);
            echo json_encode(array('error'=>'Unable to save file.'));
        }
    }

    public function actionCheckTicket(){
        $ticket_code = trim(Yii::app()->request->getParam('ticket'));
        if(!$ticket_code || strlen($ticket_code) != 16){
            http_response_code(400);
            echo json_encode(array('error'=>'wrong_data'));
            return;
        }
        $ticket = Ticket::model()->find('code=:code', array(':code'=>$ticket_code));

        if($ticket){
            $checkGame = Game::model()->find('ticket=:ticket', array(':ticket'=>$ticket->code));
            if($checkGame){
                echo json_encode(array('error'=>'taken', 'game_title'=>$checkGame->title));
                return;
            }

            $result['id'] = $ticket->id;
            $result['code'] = $ticket->code;
            $result['firstname'] = $ticket->firstname? $ticket->firstname : '';
            $result['lastname'] = $ticket->lastname? $ticket->lastname : '';
            $result['email'] = $ticket->email? $ticket->email : '';
            $result['company'] = $ticket->company? $ticket->company : '';
            $result['phone'] = $ticket->phone? $ticket->phone : '';
            $result['website'] = $ticket->website? $ticket->website : '';
            $result['country'] = $ticket->country? $ticket->country : '';
            $result['city'] = $ticket->city? $ticket->city : '';

            echo json_encode($result);
        }else{
            echo json_encode(array('error'=>'wrong_code'));
        }
    }

    public function actionAddGame(){

        $request = json_decode(file_get_contents('php://input'), true);

        #file_put_contents(Yii::app()->params['htdocsPath'].'/game_request.txt', print_r($request, true));

        $ticket = Ticket::model()->find('code=:code', array(':code'=>$request['step1']['ticket']['full']));

        if(!$ticket){
            echo json_encode(array('error'=>'wrong_code'));
            return;
        }

        $checkGame = Game::model()->find('ticket=:ticket', array(':ticket'=>$ticket->code));
        if($checkGame){
           echo json_encode(array('error'=>'taken', 'game_title'=>$checkGame->title));
           return;
        }

        $game = new Game();
        $game->category_id = 0;

        $game->ticket = $request['step1']['ticket']['full'];
        $game->ticket_id = $ticket->id;
        $game->title = $request['step2']['game']['title'];
        $game->description = $request['step2']['game']['description'];

        $game->author = @$request['step3']['dev']['author'];
        $game->author_type = $request['step3']['dev']['type'];

        $game->video = $request['step2']['game']['linkVideo'];

        $game->contact_person = $request['step3']['dev']['name'];
        $game->email = $request['step3']['dev']['email'];
        $game->phone = $request['step3']['dev']['phone'];
        $game->skype = @$request['step3']['dev']['skype'];
        $game->team_size = $request['step3']['dev']['team'];

        $game->lynch = @(int)$request['step5']['lynch']['add'];
        if($game->lynch){
            $game->lynch_drink = (int)$request['step5']['lynch']['drink'];
        }


        $game->gammplay = @(int)$request['step6']['play']['add'];
        if($game->gammplay){
            $game->showcase_device = implode(',', array_keys($request['step6']['play']['device']));
            $showcase_time = array();
            foreach($request['step6']['play']['showcase'] as $showcase){
                if(isset($showcase['checked']) && $showcase['checked']){
                    $showcase_time[] = $showcase['title'];
                }
            }
            $game->showcase_time = implode('|', $showcase_time);
        }

        $game->f2p = (isset($request['step2']['game']['freeToPlay']))? (int)$request['step2']['game']['freeToPlay'] : 0;

        $game->stage = $request['step2']['game']['devStage'];
        $game->location = $request['step3']['dev']['city'].', '.$request['step3']['dev']['country'];

        $links = array();
        $links['company'] = @$request['step3']['dev']['site'];
        $game->link = serialize($links);

        $platforms = array();
        foreach($request['step2']['game']['platform'] as $platform){
            if(isset($platform['checked']) && $platform['checked']){
                $platforms[$platform['id']] = array('id'=>$platform['id'], 'title'=>$platform['title']);
                if($platform['childs']){
                    foreach($platform['childs'] as $subplatform){
                        if(isset($subplatform['checked']) && $subplatform['checked']){
                            $platforms[$platform['id']]['childs'][$subplatform['id']] =array('id'=>$subplatform['id'], 'title'=>$subplatform['title'], 'link'=>$subplatform['link'], 'public_link'=>$subplatform['public_link']);
                        }
                    }
                }
            }
        }
        $game->platforms = serialize($platforms);

        $technologies = array();
        foreach($request['step2']['game']['tech'] as $technology){
            if(isset($technology['checked']) && $technology['checked']){
                $technologies[] = array('id'=>$technology['id'], 'title'=>$technology['title'], 'comment'=>$technology['comment']);
            }
        }
        $game->technology = serialize($technologies);

        $game->premium = (isset($request['step2']['game']['premium']))? (int)$request['step2']['game']['premium'] : 0;
        $game->multiplayer = (isset($request['step2']['game']['multiplayer']))? (int)$request['step2']['game']['multiplayer'] : 0;

application/views/awards/_game.php
<?php
$classes = array();

if($data->awards) $classes[] = 'dg-awards';
if($data->lynch) $classes[] = 'dg-game-lynch';
if($data->gammplay) $classes[] = 'dg-gamm-play';

$platforms = unserialize($data->platforms);
foreach($platforms as $platform) {
    $classes[] = 'dg-platform-'.$platform['id'];
}

$technologies = unserialize($data->technology);
foreach($technologies as $technology){
    if($technology['title'] == 'Other'){
        continue;
    }
    $classes[] = 'dg-technology-'.$technology['id'];
}
?>
<div class="dg-game <?= implode($classes, ' '); ?>" <?php if(!$data->approved) echo 'style="opacity: 0.7;"' ?>>
    <div class="dg-game-ico">
        <?php
            if($data->icon){
                echo CHtml::link('<img src="http://'.$_SERVER['SERVER_NAME'].$data->icon.'" />', array('awards/gameview', 'id'=>$data->id, '_conference'=>Yii::app()->conf), array('class'=>'game-url', 'data-id'=>$data->id));
            }else{
                echo CHtml::link('<img src="http://'.$_SERVER['SERVER_NAME'].'/i/awards/ico/game_icon.png" />', array('awards/gameview', 'id'=>$data->id, '_conference'=>Yii::app()->conf), array('class'=>'game-url', 'data-id'=>$data->id));
            }
        ?>
    </div>
    <div class="dg-game-info">
        <div class="dg-game-title"><?= $data->title; ?></div>
        <div class="dg-game-description"><?= $data->description; ?></div>
        <div>
            <?= CHtml::link('game', array('awards/gameview', 'id'=>$data->id, '_conference'=>Yii::app()->conf), array('class'=>'dg-button game-url', 'data-id'=>$data->id)); ?>
            <ul class="dg-game-submitted">
                <?= ($data->awards)? '<li class="dg-awards"><a title="DevGAMM Awards Nominee"></a></li>' : '' ?>
                <?= ($data->lynch)? '<li class="dg-game-lynch"><a title="Game Lynch Candidate"></a></li>' : '' ?>
                <?= ($data->gammplay)? '<li class="dg-gamm-play"><a title="GAMM:Play Showcase"></a></li>' : '' ?>
            </ul>
        </div>
    </div>
</div>

application/views/awards/game.php
<?php
$screenshoots = explode(',', $game->screenshoots);
$links = unserialize($game->link);
$gamelinks = array();

$platforms = unserialize($game->platforms);
foreach($platforms as $platform){
    if(isset($platform['childs']) && is_array($platform['childs']) && count($platform['childs'])){
        foreach($platform['childs'] as $subplatform){
            if(trim($subplatform['link'])){
                $platformModel = GameCategoryNew::model()->findByPk($subplatform['id']);
                if($platformModel && $platformModel->icon){
                    $subplatform['icon'] = $platformModel->icon;
                }
                $gamelinks[] = $subplatform;
            }
        }
    }
}

if(strpos($game->video, 'youtu')){
    if(strpos($game->video, '/embed/')){// /embed/video_id
        if(preg_match("|^.+/embed/(.*)|i", $game->video, $matches)){
            $yt_video = $matches[1];
        }
    }elseif(strpos($game->video, '/watch')){// /watch?v=video_id
        if(preg_match("|^.+v=(.*)|i", $game->video, $matches)){
            $yt_video = $matches[1];
        }
    }else{// youtu.be/video_id
        if(preg_match("|^.*youtu.be/(.*)|i", $game->video, $matches)){
            $yt_video = $matches[1];
        }
    }
}
?>
<div class="dg-content-wrapper" style="padding: 0">
    <h3><?= $game->title; ?></h3>
    <div class="clearfix">
        <div class="dg-col_1">
            <div class="dg-media_active">
                <?php if(isset($yt_video)):  ?>
                    <iframe src="http://www.youtube.com/embed/<?=$yt_video;?>" frameborder="0"></iframe>
                <?php else: ?>
                    <img src="<?= 'http://'.$_SERVER['SERVER_NAME'].$screenshoots[0]; ?>" />
                <?php endif; ?>
            </div>
            <div class="dg-medialist">
                <?php if(isset($yt_video)): ?>
                    <div class="dg-media">
                        <div class="dg-overlay"></div>
                        <iframe src="http://www.youtube.com/embed/<?=$yt_video;?>" frameborder="0"></iframe>
                    </div>
                <?php endif; ?>
                <?php
                $screenshoots = explode(',', $game->screenshoots);
                foreach($screenshoots as $screenshot):
                    ?>
                    <div class="dg-media">
                        <div class="dg-overlay"></div>
                        <img src="<?= 'http://'.$_SERVER['SERVER_NAME'].$screenshot; ?>" />
                    </div>
                <?php endforeach ?>
            </div>
            <div>
                <h3>Summary</h3>
                <p>
                    <b>Title:</b> <?= $game->title; ?>
                </p>
                <p>
                    <b>Description:</b> <?= $game->description; ?>
                </p>
                <?= (!isset($yt_video))? '<p><b>Gameplay video:</b> <a href="'.$game->video.'" target="_blank">'.$game->video.'</a></p>': ''; ?>
                <p>
                    <b>Author:</b> <?= $game->author; ?><br/>
                    <b>Website:</b> <a href="<?= $links['company']; ?>" target="_blank"><?= $links['company']; ?></a><br/>
                    <b>Location:</b> <?= $game->location; ?><br/>
                </p>
                <p>
                    <div>
                    <b>Stage of development:</b>
                        <?php
                            switch($game->stage){
                                case 1:
                                    echo 'prototype';
                                    break;
                                case 2:
                                    echo 'alpha';
                                    break;
                                case 3:
                                    echo 'beta';
                                    break;
                                case 4:
                                    echo 'completed';
                                    break;
                                case 5:
                                    echo 'released';
                                    break;
                            }
                        ?>
                    </div>
                    <div>
                        <b>Technology:</b>
                        <?php
                        $technologies = unserialize($game->technology);
                        $technologiesArray = array();
                        foreach($technologies as $technology){
                            $technologiesArray[] = (!empty($technology['comment']))? $technology['title'].': '.$technology['comment'] : $technology['title'];
                        }
                        echo implode(', ', $technologiesArray);
                        ?>
                    </div>
                </p>
                <p>
                    <div><b>Free-to-play:</b> <?= ($game->f2p)? 'yes' : 'no'; ?></div>
                    <div><b>Multiplayer:</b> <?= ($game->multiplayer)? 'yes' : 'no'; ?></div>
                </p>

                <?php $this->renderPartial('../participant/_dgbp_start', array('participant'=>'partner')); ?>

                <p ng-init="edit_own_data=false">
                    <img align="left" style="padding-right:5px;" alt="" src="<?= 'http://'.$_SERVER['SERVER_NAME']; ?>/i/mail_icon.png"/>
                    <a title="<?= $partner->name_en; ?>" ng-click="makeAppointment('<?= $partner->id; ?>', 'partner')">
                        <?= Yii::t('app', 'Email developer'); ?></a>
                </p>
                <?php $this->renderPartial('../participant/_dgbp_end'); ?>

            </div>
        </div>
        <div class="dg-col_2">
            <div class="dg-gameinfo-block text-center">
                <p>
                    <ul class="dg-game-submitted">
                        <?= ($game->awards)? '<li class="dg-awards"><a title="DevGAMM Awards Nominee"></a></li>' : ''; ?>
                        <?= ($game->lynch)? '<li class="dg-game-lynch"><a title="Game Lynch Candidate"></a></li>' : ''; ?>
                        <?= ($game->gammplay)? '<li class="dg-gamm-play"><a title="GAMM:Play Showcase"></a></li>' : ''; ?>
                    </ul>
                </p>
                <p>
                    <?php if($game->icon): ?>
                        <img src="<?= 'http://'.$_SERVER['SERVER_NAME'].$game->icon; ?>" />
                    <?php else: ?>
                        <img src="<?= 'http://'.$_SERVER['SERVER_NAME']; ?>/i/awards/ico/game_icon.png" />
                    <?php endif; ?>
                </p>
                <p><b><?= $game->title; ?></b></p>
                <div class="dg-socials">
                    <a onclick="Share.vkontakte('<?=$game->title;?>')"><img src="http://w.sharethis.com/images/vkontakte_32.png" /></a>
                    <a onclick="Share.facebook('<?=$game->title;?>')"><img src="http://w.sharethis.com/images/facebook_32.png" /></a>
                    <a onclick="Share.twitter('<?=$game->title;?>')"><img src="http://w.sharethis.com/images/twitter_32.png" /></a>
                    <a onclick="Share.google('<?=$game->title;?>')"><img src="http://w.sharethis.com/images/googleplus_32.png" /></a>
                </div>
            </div>
            <?php foreach($gamelinks as $link): ?>
                <?php if(isset($link['public_link']) && $link['public_link'] == 0) continue; ?>
                <div class="dg-gameinfo-block text-center">
                    <p>
                        <b><?= $link['title'] ?> version</b>
                    </p>
                    <p style="position: relative;">
                        <?php if(isset($link['icon']) && $link['icon']): ?>
                            <img src="<?= 'http://'.$_SERVER['SERVER_NAME'].$link['icon'] ?>" class="version-ico" />
                        <?php endif; ?>
                        <a href="<?= $link['link'] ?>" target="_blank" class="dg-button">play</a>
                    </p>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <br/>
    <div class="clearfix">
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES * * */
            var disqus_shortname = 'devgamm';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
    </div>
</div>
<script>
    $('document').ready(function () {
        /** change main photo */
        $('.dg-media>.dg-overlay').click(function (){
            $('.dg-media_active').html($(this).parent().html());
            $('.dg-media').removeClass('dg-dim');
            $(this).parent().addClass('dg-dim');
        });

        $('.dg-medialist>div:first').addClass('dg-dim');

        var shareUrl = (window.location != window.parent.location) ? document.referrer: document.location;
        Share = {
            vkontakte: function(ptitle, pimg, text) {
                url  = 'http://vkontakte.ru/share.php?';
                url += 'url='          + encodeURIComponent(shareUrl);
                url += '&title='       + encodeURIComponent(ptitle);
/**                url += '&description=' + encodeURIComponent(text);
               url += '&image='       + encodeURIComponent(pimg);  */
                url += '&noparse=true';
                Share.popup(url);
            },
            odnoklassniki: function(text) {
                url  = 'http://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=1';
                url += '&st.comments=' + encodeURIComponent(text);
                url += '&st._surl='    + encodeURIComponent(shareUrl);
                Share.popup(url);
            },
            facebook: function(purl, ptitle, pimg, text) {
                url  = 'http://www.facebook.com/sharer.php?s=100';
                url += '&p[title]='     + encodeURIComponent(ptitle);
/**                url += '&p[summary]='   + encodeURIComponent(text); */
                url += '&p[url]='       + encodeURIComponent(shareUrl);
/**                url += '&p[images][0]=' + encodeURIComponent(pimg); */
                Share.popup(url);
            },
            twitter: function(ptitle) {
                url  = 'http://twitter.com/share?';
                url += 'text='      + encodeURIComponent(ptitle);
                url += '&url='      + encodeURIComponent(shareUrl);
                url += '&counturl=' + encodeURIComponent(shareUrl);
                Share.popup(url);
            },
            mailru: function(ptitle, pimg, text) {
                url  = 'http://connect.mail.ru/share?';
                url += 'url='          + encodeURIComponent(shareUrl);
                url += '&title='       + encodeURIComponent(ptitle);
/**                url += '&description=' + encodeURIComponent(text); */
/**                url += '&imageurl='    + encodeURIComponent(pimg); */
                Share.popup(url)
            },
            google: function() {
                url  = 'https://plus.google.com/share?';
                url += 'url='          + encodeURIComponent(shareUrl);
                Share.popup(url)
            },

            popup: function(url) {
                window.open(url,'','toolbar=0,status=0,width=626,height=436');
            }
        };

    });
</script>

application/views/awards/index.php
<?php
$classesBlue = array();
$classesRed = array();
$games = $dataProvider->getData();

foreach($games as $game){
    if($game->awards) $classesRed['dg-awards'] = 'awards';
    if($game->lynch) $classesRed['dg-game-lynch'] = 'game lynch';
    if($game->gammplay) $classesRed['dg-gamm-play'] = 'gamm:play';

    $platforms = unserialize($game->platforms);

    if(is_array($platforms)){
        foreach($platforms as $platform) {
            $classesBlue['platform-'.$platform['id']] = $platform['title'];
        }
    }

    $technologies = unserialize($game->technology);

    foreach($technologies as $technology){
        if($technology['title'] == 'Other'){
            continue;
        }
        $classesBlue['technology-'.$technology['id']] = $technology['title'];
    }
}
//ksort($classesBlue);
?>
<div class="dg-content-wrapper dg-page">
<div class="dg-tags filter option-set clearfix " data-filter-group="blue">
    <a href="#" class="dg-active" data-filter="*" >All</a>
    <?php
    foreach($classesBlue as $class => $label) {
        echo '<a href="#" data-filter-value=".dg-'.$class.'">'.$label.'</a>';
    }
    ?>
</div>
<div class="dg-tags dg-tag-type filter option-set clearfix " data-filter-group="red">
    <a href="#" class="dg-active" data-filter="*" >All</a>
    <?php foreach($classesRed as $class => $label) echo '<a href="#" data-filter-value=".'.$class.'">'.$label.'</a>'; ?>
</div>
<div class="dg-sepline" style="clear: none;"></div>

<div class="dg-games" id="dg-games" style="width: 100%; display: inline-block;">
    <?php
    $data = $dataProvider->getData();
    foreach($data as $i => $item)
        Yii::app()->controller->renderPartial('_game',
            array('index' => $i, 'data' => $item, 'widget' => $this));
    ?>
</div>

<div style="height: 100px;"></div>

<script>
    $(document).ready(function(){
        var $container = $('#dg-games');
        var filters = {};

        $container.isotope({
            itemSelector: '.dg-game',
            masonry: {
                columnWidth: 380
            }
        });

        /** filter buttons */
        $('.filter a').click(function(){
            var $this = $(this);
            /** don't proceed if already selected */
            if ( $this.hasClass('dg-active') ) {
                return false;
            }

            var $optionSet = $this.parents('.option-set');
            /** change selected class */
            $optionSet.find('.dg-active').removeClass('dg-active');
            $this.addClass('dg-active');

            /** store filter value in object
             i.e. filters.color = 'red' */
            var group = $optionSet.attr('data-filter-group');
            filters[ group ] = $this.attr('data-filter-value');
            /** convert object into array */
            var isoFilters = [];
            for ( var prop in filters ) {
                isoFilters.push( filters[ prop ] )
            }
            var selector = isoFilters.join('');
            console.log(selector);
            $container.isotope({ filter: selector });

            return false;
        });


        $('.game-url').each(function(){
            var gameId = $(this).data('id');
            var url = (window.location != window.parent.location) ? document.referrer: document.location;

            if(url.toString().indexOf('?') > 0){
                url += '&gameId='+gameId;
            }else{
                url += '?gameId='+gameId;
            }
            var d = document.createElement('div');
            url = $(d).html(url).text();
            $(this).attr('href', url);
        });

    });
</script>

application/views/awards/register.php
<div ng-app="DGA" ui-view></div>