application/controllers/ConsoleController.php
<?php

Yii::import('application.widgets.Participant');

class ConsoleController extends Controller
{
    /**
     * _isJustReturnValue
     * returns value flag, if true getstats actions returns data, otherwise echo data and exit
     *
     * @var bool
     * @access private
     */
    private $_isJustReturnValue = false;

    /**
     * _isEchoCSV
     * returns data flag, if true - returns data as csv file
     *
     * @var bool
     * @access private
     */
    private $_isEchoCSV = false;

    /**
     * _csvArray
     * csv data container
     *
     * @var array
     * @access private
     */
    private $_csvArray = array();

    private $_userReports = array();
    private $_userCharttypes = array();

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions' => array('login', 'error'),
                'users' => array('*'),
            ),
            array('allow',
                'users' => array('@'),
            ),
            array('deny',
                'users' => array('*'),
            ),
        );
    }

    /**
     * actionIndex
     * default action
     * @access public
     * @return void
     */
    public function actionIndex()
    {
        $this->render('index');
    }

    /**
     * actionLogin
     * action provide login form and login user whether he has been authenticated
     * @access public
     * @return void
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        $model = new LoginForm();

        if (isset($_POST['LoginForm']))
        {
            $model->attributes = $_POST['LoginForm'];

            if ($model->validate() && $model->login())
            {
                $this->redirect('/');
            }
        }

        return $this->render('login', array(
            'model' => $model,
        ));
    }

    /**
     * actionLogout
     * log out user from the system
     * @access public
     * @return void
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect('login');
    }

    public function actionPartners($action = null)
    {
        $this->_processParticipantAction('partners', 'Partner', $action);
    }

    public function actionExperts($action = null)
    {
        $this->_processParticipantAction('experts', 'Expert', $action);
    }

    public function actionSponsors($action = null)
    {
        $this->_processParticipantAction('sponsors', 'Sponsor', $action);
    }

    public function actionSpeakers($action = null)
    {
        $this->_processParticipantAction('speakers', 'Speaker', $action);
    }

    public function actionParticipants($action = null)
    {
        $this->_processParticipantAction('participants', 'Participant', $action);
    }

    public function actionDiscussionpanels($action = null)
    {
        $this->_processParticipantAction('discussionPanels', 'DiscussionPanel', $action);
    }

    public function actionApprove($id, $approve)
    {
        if (empty($id))
        {
            throw new CHttpException('Incorrect id specified');
        }
        if (Yii::app()->Core->approveGame($id, isset($_GET['approve']) && $_GET['approve'] ? 1 : 0))
        {
            echo 1;
        }
        Yii::app()->end();
    }

    public function actionGames($action = null, $type = null)
    {
        if (empty($action))
        {
            $action = 'list';
        }
        switch ($action)
        {
            case 'list':
                $this->render('games', array('type' => $type, 'data' => Yii::app()->Core->getGamesForConsole(array($type => 1))));
                break;
            case 'save':
                if (empty($_POST) || empty($type))
                {
                    throw new CHttpException('Empty data for save');
                }
                if ('games' == $type && empty($_POST['id']))
                {
                    throw new CHttpException('Can\'t update game without id');
                }
                $id = null;
                if (isset($_POST['id']))
                {
                    $id = $_POST['id'];
                    unset($_POST['id']);
                }
                try
                {
                    switch ($type)
                    {
                        case 'games':
                            Yii::app()->Core->updateGame($id, $_POST);
                            break;
                        case 'categories':
                            Yii::app()->Core->saveGameCategory($_POST, $id);
                            break;
                        default:
                            throw new CHttpException('Unknown type: {' . $type . '}');
                            break;
                    }
                }
                catch (Exception $e)
                {
                    echo 'Some problem with saving data: ' . $e->getMessage();
                    Yii::app()->end();
                }
                break;
            case 'approve':
                if (empty($_POST['id']) || !isset($_POST['is_approved']))
                {
                    throw new CHttpException('Empty data for approve');
                }
                Yii::app()->Core->approveGame($_POST['id'], $_POST['is_approve']);
                break;
            case 'up':
            case 'down':
                if (empty($_POST['id']))
                {
                    throw new CHttpException('Incorrect data for updating rating');
                }
                try
                {
                    echo Yii::app()->Core->updateRating('Game', $_POST['id'], $action);
                }
                catch (Exception $e)
                {
                    echo 0;
                }
                break;
            case 'remove':
                if (empty($_POST['id']))
                {
                    throw new CHttpException('Incorrect data for delete');
                }
                try
                {
                    Yii::app()->Core->deleteGame($_POST['id']);
                }
                catch (Exception $e)
                {
                    echo $e->getMessage();
                    Yii::app()->end();
                }
                break;
            case 'getCSV':
                Yii::app()->Core->getCSV('Game');
                break;
            default:
                throw new CHttpException('Incorrect action specified');
                break;
        }
    }

    protected function _processParticipantAction($type, $model, $action)
    {
        switch ($action)
        {
            case 'list':
                $this->render('participants', array('type' => $type, 'data' => Yii::app()->Core->getParticipantsForConsole($model)));
                break;
            case 'save':
            case 'save_speaker_category':
            case 'save_discussion_category':
                if (empty($_POST))
                {
                    throw new CHttpException('Empty data for save');
                }
                $id = null;
                if (isset($_POST['id']))
                {
                    $id = $_POST['id'];
                    unset($_POST['id']);
                }
                try
                {
                    switch ($action)
                    {
                        case 'save':
                            Yii::app()->Core->saveParticipant($model, $_POST, $id);
                            break;
                        case 'save_speaker_category':
                        case 'save_discussion_category':
                            Yii::app()->Core->saveCategory('save_speaker_category' == $action ? 'SpeakerCategory' : 'DiscussionCategory', $_POST, $id);
                            break;
                    }
                }
                catch (Exception $e)
                {
                    echo 'Some problem with saving data: ' . $e->getMessage();
                    Yii::app()->end();
                }
                break;
            case 'up':
            case 'down':
                if (empty($_POST['id']))
                {
                    throw new CHttpException('Incorrect data for updating rating');
                }
                try
                {
                    echo Yii::app()->Core->updateRating($model, $_POST['id'], $action);
                }
                catch (Exception $e)
                {
                    echo 0;
                }
                break;
            case 'remove':
                if (empty($_POST['id']))
                {
                    throw new CHttpException('Empty data for delete');
                }
                if ('speakers' == $type)
                {
                    if (isset($_POST['participant']))
                    {
                        try
                        {
                            Yii::app()->Core->deleteParticipant($model, $_POST['id']);
                        }
                        catch (Exception $e)
                        {
                            echo $e->getMessage();
                            Yii::app()->end();
                        }
                    }
                    else
                    {
                        $data = Yii::app()->Core->getParticipants('Speaker', array('category_id' => $_POST['id']));
                        if (empty($data))
                        {
                            Yii::app()->Core->deleteCategory('SpeakerCategory', $_POST['id']);
                        }
                        else
                        {
                            echo 'You can\'t delete category where speakers are present!';
                            Yii::app()->end();
                        }
                    }
                }
                else
                {

application/controllers/SettingsController.php
<?php

class SettingsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='main';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('console/login'));
        }

        $this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('console/login'));
        }


        $model=new Settings;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Settings']))
		{
			$model->attributes=$_POST['Settings'];
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('console/login'));
        }


        $model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Settings']))
		{
			$model->attributes=$_POST['Settings'];
			if($model->save())
				$this->redirect(array('admin'));

			Yii::app()->cache->flush();
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('console/login'));
        }


        $this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
    public function actionIndex()
    {
        $settings = Settings::model()->findAll();
		$settingSkipId = array(2,3,4);
		$settingStripTagsId = array(11,12,13,14,15,16,17,19);
		$settingDatesId = array(11,12,13);
		$result = array();
		foreach($settings as $setting){
			if(!in_array($setting->id, $settingSkipId)){
				if(in_array($setting->id, $settingStripTagsId)){
					$result[$setting->name]	 = strip_tags(preg_replace("/\r\n|\r|\n/",'<br/>',$setting->value));
				}else{
					$result[$setting->name]	 = $setting->value;
				}

				if(in_array($setting->id, $settingDatesId))
					$result[$setting->name]	 = date('Y-m-d',strtotime($result[$setting->name]));
			}
		}
        echo json_encode($result);
    }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
        if(Yii::app()->user->isGuest){
            $this->redirect(array('console/login'));
        }


        $model=new Settings('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Settings']))
			$model->attributes=$_GET['Settings'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Settings the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Settings::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Settings $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='settings-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

application/views/layouts/awards.php
<?php Yii::app()->clientScript->registerPackage('awards'); ?>
<input type="hidden" id="currentConferenceID" value="<?= Yii::app()->conf; ?>" />
<input type="hidden" id="currentConferenceConsoleUrl" value="<?= 'http://'.$_SERVER['SERVER_NAME']; ?>" />
<?= $content; ?>

application/views/layouts/game.php
<?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>
<input type="hidden" id="currentConferenceID" value="<?= Yii::app()->conf; ?>" />
<input type="hidden" id="currentConferenceConsoleUrl" value="<?= 'http://'.$_SERVER['SERVER_NAME']; ?>" />
<?= $content; ?>

application/views/layouts/login.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=<?= Yii::app()->charset; ?>" />

        <title><?= CHtml::encode($this->pageTitle); ?></title>

        <?php
        Yii::app()->clientScript->registerCoreScript('jquery')
                                ->registerPackage('bootstrap')
                                ->registerCssFile('login.css');
        ?>
    </head>
    <body>

    <div>
      <?=$content?>
    </div>

  </body>

</html>

application/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en-us">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=<?= Yii::app()->charset; ?>" />
        <title><?= CHtml::encode($this->pageTitle); ?></title>
        <?php Yii::app()->clientScript->registerCoreScript('jquery')
                                      ->registerCoreScript('ckeditor')
                                      ->registerPackage('bootstrap')
                                      ->registerCssFile('admin.css'); ?>
    </head>
    <body>
    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand" href="/"><?= Yii::app()->name; ?>, <?= Yii::app()->Core->conf; ?></a>
            <ul class="nav">
                <?php if ($this->isUserHasAccess('games')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Games <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'all')); ?>">All</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'approved')); ?>">Approved</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'notapproved')); ?>">Not approved</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'lynch')); ?>">Lynch</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'gammplay')); ?>">GaMM:Play</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'list', 'type' => 'categories')); ?>">Game categories</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/games', array('action' => 'getCSV')); ?>">Export games as csv</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if ($this->isUserHasAccess('participants')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Experts <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/experts', array('action' => 'list')); ?>">List</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/experts', array('action' => 'conversation')); ?>">Conversations</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if ($this->isUserHasAccess('sponsors')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sponsors <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/sponsors', array('action' => 'list')); ?>">List</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/sponsors', array('action' => 'conversation')); ?>">Conversations</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if ($this->isUserHasAccess('partners')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Partners <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/partners', array('action' => 'list')); ?>">List</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/partners', array('action' => 'conversation')); ?>">Conversations</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if ($this->isUserHasAccess('speakers')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Speakers <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/speakers', array('action' => 'list')); ?>">List</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/speakers', array('action' => 'conversation')); ?>">Conversations</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/speakers', array('action' => 'categories')); ?>">Categories</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if ($this->isUserHasAccess('discussion_panels')) { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Discussion Panels <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= Yii::app()->createUrl('console/discussionpanels', array('action' => 'list')); ?>">Participants</a></li>
                            <li><a href="<?= Yii::app()->createUrl('console/discussionpanels', array('action' => 'categories')); ?>">Categories</a></li>
                        </ul>
                    </li>
                <?php } ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Showcase <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= Yii::app()->createUrl('showcase/update'); ?>">Udate</a></li>
                        <li><a href="<?= Yii::app()->createUrl('showcase/index'); ?>">View</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Game info <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= Yii::app()->createUrl('gameCategoryNew/admin'); ?>">Platforms</a></li>
                        <li><a href="<?= Yii::app()->createUrl('gameTechnology/admin'); ?>">Technology</a></li>
                        <li><a href="<?= Yii::app()->createUrl('gameNomination/admin'); ?>">Nomination</a></li>
                    </ul>
                </li>
                <li><a href="<?= Yii::app()->createUrl('settings/admin'); ?>">Settings</a></li>
            </ul>
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Conferences <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <?php foreach (Yii::app()->Core->conferences as $k => $v) { ?>
                            <li><a href="/?_conference=<?= $k; ?>"><?= $v; ?></a></li>
                        <?php } ?>
                    </ul>
                </li>
                <li class="divider-vertical"></li>
                <li><a href="<?=Yii::app()->createUrl('console/logout')?>">Logout</a></li>
                <li class="divider-vertical"></li>
                <li>
                    <p class="navbar-text">working as: <b><?=Yii::app()->user->id;?></b> </p>
                </li>
            </ul>
        </div>
    </div>
    <div>
      <?=$content?>
    </div>
  </body>
</html>

application/views/layouts/participant.php
<?php Yii::app()->clientScript->registerPackage('awards'); ?>
<input type="hidden" id="currentConferenceID" value="<?= Yii::app()->conf; ?>" />
<input type="hidden" id="currentConferenceConsoleUrl" value="<?= 'http://'.$_SERVER['SERVER_NAME']; ?>" />
<?= $content; ?>